name: Terraform Plan and Output ECR URL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # Adjust the version as needed

    - name: Initialize Terraform
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan -out=plan.out

    - name: Show Planned State
      run: terraform show plan.out

    # Optional: If you have outputs configured in Terraform (e.g., ECR URL), you can retrieve it with terraform output
    - name: Extract ECR URL
      run: terraform output ecr_url

    # Example of how you might store the output into a GitHub Action output or secret
    - name: Save ECR URL as GitHub Secret (Optional Step)
      run: echo "ECR_URL=$(terraform output -raw ecr_url)" >> $GITHUB_ENV

