name: Terraform Apply Workflow

on:
  push:
    branches:
      - main  # Triggers on push to the main branch (you can change this if needed)

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest version of the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      # Step 3: Navigate to the correct directory (starter-project/infrastructure/terraform-manifest)
      - name: Initialize Terraform
        run: terraform init
        working-directory: starter-project/infrastructure/terraform-manifest

      # Step 4: Apply Terraform configuration with auto-approve
      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: starter-project/infrastructure/terraform-manifest
